### Criar URL
POST http://localhost:3333/api/links
Content-Type: application/json

{
  "originalUrl": "https://www.urlaleatoria.com"
}

### Listar URLs
GET http://localhost:3333/api/links

### Editar URLs
PUT http://localhost:3333/api/links/1
Content-Type: application/json

{
  "legenda": "Meu site favorito",
  "originalUrl": "https://www.novosite.com"
}

###Excluir URLs
DELETE http://localhost:3333/api/links/ygVcqVPE
