-- ALTER TABLE "urls" ADD COLUMN "legenda" text;--> statement-breakpoint
-- ALTER TABLE "urls" ADD COLUMN "clicks" integer DEFAULT 0;--> statement-breakpoint
-- ALTER TABLE "urls" ADD COLUMN "updated_at" timestamp DEFAULT now();